"use strict";

// Per-file element sets, keyed by upload slot ("reactant" | "product" | "ts_guess"),
// so the GenECP panel can offer the union of everything actually uploaded.
const uploads = {
  reactant: null, // { token, elements, atom_count }
  product: null,
  ts_guess: null,
};

const el = (id) => document.getElementById(id);

el("tips-btn").addEventListener("click", () => {
  el("tips-panel").classList.toggle("hidden");
});

// Session-wide: once enabled, every study submitted from here on uses
// "pbs" as its executor instead of "local", until toggled back off.
let pbsEnabled = false;
let pbsTemplateLoaded = false;

el("pbs-toggle-btn").addEventListener("click", async () => {
  pbsEnabled = !pbsEnabled;
  el("pbs-toggle-btn").textContent = pbsEnabled ? "PBS submission: ON" : "Enable PBS submission";
  el("pbs-toggle-btn").classList.toggle("active", pbsEnabled);
  el("pbs-warning").classList.toggle("hidden", !pbsEnabled);

  // Fetch the default script once, the first time PBS mode is turned
  // on -- after that the box keeps whatever the user has edited, even
  // across toggling off and back on, so an in-progress edit is never
  // lost.
  if (pbsEnabled && !pbsTemplateLoaded) {
    const textarea = el("pbs-script-textarea");
    textarea.value = "Loading...";
    try {
      const res = await fetch("/api/pbs_template");
      const data = await res.json();
      textarea.value = data.template;
      pbsTemplateLoaded = true;
    } catch (e) {
      textarea.value = `Couldn't load the default template: ${e.message}`;
    }
  }
});

// The script starts read-only (view mode) so it can't be changed by
// accident -- "Edit" unlocks it, "Save" locks it back. The textarea's
// value is what's actually submitted either way; Save is a UI
// affordance confirming the edit is done, not a separate persistence
// step.
el("pbs-edit-btn").addEventListener("click", () => {
  const textarea = el("pbs-script-textarea");
  textarea.readOnly = false;
  textarea.focus();
  el("pbs-edit-btn").classList.add("hidden");
  el("pbs-save-btn").classList.remove("hidden");
});

el("pbs-save-btn").addEventListener("click", () => {
  el("pbs-script-textarea").readOnly = true;
  el("pbs-save-btn").classList.add("hidden");
  el("pbs-edit-btn").classList.remove("hidden");
});

function studyType() {
  return document.querySelector('input[name="study_type"]:checked').value;
}

function updateStudyTypeVisibility() {
  const type = studyType();
  const mechanism = type === "mechanism";
  const tsSearch = type === "ts_search";
  const showProductTsGuess = mechanism || tsSearch;

  el("field-product").classList.toggle("hidden", !showProductTsGuess);
  el("field-ts-guess").classList.toggle("hidden", !showProductTsGuess);
  el("step-irc").classList.toggle("hidden", !mechanism);
  el("step-verification").classList.toggle("hidden", !mechanism);
  el("energy-units-field").classList.toggle("hidden", !mechanism);
  el("gcorr-block").classList.toggle("hidden", tsSearch);
  el("ts-recover-row").classList.toggle("hidden", !tsSearch);

  el("reactant-label").textContent = tsSearch ? "Reactant file (optional for TS search)" : mechanism ? "Reactant file" : "Structure file";
  el("product-label").textContent = tsSearch ? "Product file (optional for TS search)" : "Product file";
  el("ts-guess-summary-text").textContent = tsSearch
    ? "TS guess file (required unless both reactant and product are given)"
    : "Optional: TS guess file (auto-generated by interpolation if omitted)";
  el("energy-section-heading").textContent = mechanism ? "6. Energy report" : "6. Export options";

  if (!tsSearch) {
    el("reactant-log-warning").classList.add("hidden");
    el("product-log-warning").classList.add("hidden");
  } else {
    updateLogWarning("reactant");
    updateLogWarning("product");
  }
}

function updateLogWarning(slot) {
  if (studyType() !== "ts_search") return;
  const upload = uploads[slot];
  const filename = upload ? (el(`${slot}-file`).files[0] || {}).name || "" : "";
  const warning = el(`${slot}-log-warning`);
  warning.classList.toggle("hidden", !upload || filename.toLowerCase().endsWith(".log"));
}

document.querySelectorAll('input[name="study_type"]').forEach((r) =>
  r.addEventListener("change", updateStudyTypeVisibility)
);
updateStudyTypeVisibility();

// ---------------------------------------------------------------- uploads

function applyUploadResult(slot, infoId, data, errorPrefix) {
  const info = el(infoId);
  if (data.ok) {
    uploads[slot] = data.body;
    info.textContent = `OK: ${data.body.atom_count} atoms (${data.body.elements.join(", ")})`;
    info.className = "file-info ok";
  } else {
    uploads[slot] = null;
    info.textContent = `${errorPrefix}: ${data.message}`;
    info.className = "file-info err";
  }
  if (slot === "reactant" || slot === "product") updateLogWarning(slot);
  renderGenecpElements();
}

async function postJSON(url, body) {
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const errBody = await res.json().catch(() => ({}));
    return { ok: false, message: errBody.detail || `HTTP ${res.status}` };
  }
  return { ok: true, body: await res.json() };
}

async function handleFileUpload(inputId, infoId, slot) {
  const input = el(inputId);
  const info = el(infoId);
  const file = input.files[0];
  if (!file) {
    uploads[slot] = null;
    info.textContent = "";
    info.className = "file-info";
    renderGenecpElements();
    return;
  }
  info.textContent = "Reading...";
  info.className = "file-info";

  const form = new FormData();
  form.append("file", file);
  let data;
  try {
    const res = await fetch("/api/analyze", { method: "POST", body: form });
    if (!res.ok) {
      const errBody = await res.json().catch(() => ({}));
      data = { ok: false, message: errBody.detail || `HTTP ${res.status}` };
    } else {
      data = { ok: true, body: await res.json() };
    }
  } catch (e) {
    data = { ok: false, message: e.message };
  }
  applyUploadResult(slot, infoId, data, "Couldn't read this file");
}

async function handleSmilesLoad(smilesInputId, infoId, slot, buttonId) {
  const smiles = el(smilesInputId).value.trim();
  const info = el(infoId);
  if (!smiles) {
    info.textContent = "Enter a SMILES string first.";
    info.className = "file-info err";
    return;
  }
  const button = el(buttonId);
  button.disabled = true;
  info.textContent = "Embedding...";
  info.className = "file-info";

  // A SMILES load supersedes any file already chosen for this slot,
  // and vice versa -- whichever was done most recently wins.
  el(smilesInputId.replace("-smiles", "-file")).value = "";

  const data = await postJSON("/api/analyze_smiles", { smiles, label: slot });
  applyUploadResult(slot, infoId, data, `Couldn't embed ${smiles}`);
  button.disabled = false;
}

el("reactant-file").addEventListener("change", () => handleFileUpload("reactant-file", "reactant-info", "reactant"));
el("product-file").addEventListener("change", () => handleFileUpload("product-file", "product-info", "product"));
el("ts-guess-file").addEventListener("change", () => handleFileUpload("ts-guess-file", "ts-guess-info", "ts_guess"));

el("reactant-smiles-load").addEventListener("click", () => handleSmilesLoad("reactant-smiles", "reactant-info", "reactant", "reactant-smiles-load"));
el("product-smiles-load").addEventListener("click", () => handleSmilesLoad("product-smiles", "product-info", "product", "product-smiles-load"));
el("ts-guess-smiles-load").addEventListener("click", () => handleSmilesLoad("ts-guess-smiles", "ts-guess-info", "ts_guess", "ts-guess-smiles-load"));

["reactant-smiles", "product-smiles", "ts-guess-smiles"].forEach((id) => {
  el(id).addEventListener("keydown", (evt) => {
    if (evt.key === "Enter") {
      evt.preventDefault();
      el(`${id}-load`).click();
    }
  });
});

// ------------------------------------------------------------ AI refine

(async () => {
  // Best-effort only -- the backend's own check is the definitive answer,
  // this just sets an informational tooltip so the button doesn't look
  // broken when there's obviously no credential configured.
  const avail = await fetch("/api/refine/available").then((r) => r.json()).catch(() => ({ available: false }));
  if (!avail.available) {
    ["reactant", "product"].forEach((slot) => {
      el(`${slot}-refine`).title = "Needs an Anthropic API credential configured on the server -- will show an error if unavailable.";
    });
  }
})();

function renderRefineResult(slot, resultId, body) {
  const resultEl = el(resultId);
  const mismatchColor = body.matches_description ? "" : ` style="color:var(--bad)"`;
  let html = `<p class="refine-note"${mismatchColor}>${body.notes}</p>`;

  if (body.pubchem_token) {
    html += `<div class="refine-suggestion">
      <span>PubChem structure available: ${body.pubchem_elements.join(", ")} (${body.pubchem_atom_count} atoms)</span>
      <button type="button" class="apply-btn" data-token="${body.pubchem_token}" data-elements='${JSON.stringify(body.pubchem_elements)}' data-count="${body.pubchem_atom_count}">Use this structure</button>
    </div>`;
  }
  if (body.smiles_token) {
    html += `<div class="refine-suggestion">
      <span>Suggested SMILES ${body.suggested_smiles}: ${body.smiles_elements.join(", ")} (${body.smiles_atom_count} atoms)</span>
      <button type="button" class="apply-btn" data-token="${body.smiles_token}" data-elements='${JSON.stringify(body.smiles_elements)}' data-count="${body.smiles_atom_count}">Use this structure</button>
    </div>`;
  }
  if (body.suggested_charge != null || body.suggested_multiplicity != null) {
    html += `<p class="refine-note">Suggested charge/multiplicity: ${body.suggested_charge ?? 0} / ${body.suggested_multiplicity ?? 1} -- adjust manually if this looks right, nothing is applied automatically.</p>`;
  }

  resultEl.innerHTML = html;

  resultEl.querySelectorAll(".apply-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      uploads[slot] = {
        token: btn.dataset.token,
        elements: JSON.parse(btn.dataset.elements),
        atom_count: parseInt(btn.dataset.count, 10),
      };
      const infoId = slot === "ts_guess" ? "ts-guess-info" : `${slot}-info`;
      const info = el(infoId);
      info.textContent = `OK: ${uploads[slot].atom_count} atoms (${uploads[slot].elements.join(", ")}) -- from AI-assisted refinement`;
      info.className = "file-info ok";
      renderGenecpElements();
      resultEl.querySelectorAll(".apply-btn").forEach((b) => (b.disabled = true));
      btn.textContent = "Applied";
    });
  });
}

async function handleRefine(slot, descId, resultId, buttonId) {
  const description = el(descId).value.trim();
  const resultEl = el(resultId);
  if (!description) {
    resultEl.innerHTML = '<p class="refine-note" style="color:var(--bad)">Enter a description first.</p>';
    return;
  }
  const upload = uploads[slot];
  if (!upload) {
    resultEl.innerHTML = '<p class="refine-note" style="color:var(--bad)">Load a structure (file or SMILES) above first.</p>';
    return;
  }

  const button = el(buttonId);
  button.disabled = true;
  resultEl.innerHTML = '<p class="refine-note">Asking Claude...</p>';

  const data = await postJSON("/api/refine", { token: upload.token, description });
  button.disabled = false;

  if (!data.ok) {
    resultEl.innerHTML = `<p class="refine-note" style="color:var(--bad)">${data.message}</p>`;
    return;
  }
  renderRefineResult(slot, resultId, data.body);
}

el("reactant-refine").addEventListener("click", () => handleRefine("reactant", "reactant-description", "reactant-refine-result", "reactant-refine"));
el("product-refine").addEventListener("click", () => handleRefine("product", "product-description", "product-refine-result", "product-refine"));

function unionElements() {
  const set = new Set();
  for (const key of ["reactant", "product", "ts_guess"]) {
    const u = uploads[key];
    if (u) u.elements.forEach((e) => set.add(e));
  }
  return Array.from(set).sort();
}

// -------------------------------------------------------------- method/basis

el("method").addEventListener("change", () => {
  el("method-custom").classList.toggle("hidden", el("method").value !== "__custom__");
});

el("basis").addEventListener("change", () => {
  const v = el("basis").value;
  el("basis-custom").classList.toggle("hidden", v !== "__custom__");
  el("genecp-panel").classList.toggle("hidden", v !== "__genecp__");
  if (v === "__genecp__") renderGenecpElements();
});

function renderGenecpElements() {
  if (el("basis").value !== "__genecp__") return;
  const container = el("genecp-elements");
  const elements = unionElements();
  if (elements.length === 0) {
    container.innerHTML = '<p class="hint" style="margin:0">Upload a structure above to list its elements here.</p>';
    return;
  }
  container.innerHTML = "";
  elements.forEach((symbol) => {
    const wrap = document.createElement("div");
    wrap.className = "genecp-element";
    wrap.innerHTML = `
      <label class="el-header">
        <input type="checkbox" class="ecp-check" data-el="${symbol}"> ${symbol}
      </label>
      <input type="text" class="ecp-name hidden" data-el="${symbol}" placeholder="e.g. LanL2DZ" value="LanL2DZ">
    `;
    container.appendChild(wrap);
    const checkbox = wrap.querySelector(".ecp-check");
    const nameInput = wrap.querySelector(".ecp-name");
    checkbox.addEventListener("change", () => nameInput.classList.toggle("hidden", !checkbox.checked));
  });
}

// -------------------------------------------------------------------- IRC

function updateIrcEndpointAvailability() {
  const ircOn = el("run-irc").checked;
  const checkbox = el("run-irc-endpoint-reopt");
  checkbox.disabled = !ircOn;
  if (!ircOn) checkbox.checked = false;
  el("irc-endpoint-hint").classList.toggle("hidden", ircOn);
}

el("run-irc").addEventListener("change", () => {
  el("irc-points-field").classList.toggle("hidden", !el("run-irc").checked);
  updateIrcEndpointAvailability();
});
updateIrcEndpointAvailability();

// ------------------------------------------------------- TS-mode distortion

el("run-ts-distortion").addEventListener("change", () => {
  el("distortion-factor-field").classList.toggle("hidden", !el("run-ts-distortion").checked);
});
el("distortion-factor-field").classList.toggle("hidden", !el("run-ts-distortion").checked);

// -------------------------------------------------------------- G-corr

el("compute-gcorr").addEventListener("change", () => {
  el("gcorr-fields").hidden = !el("compute-gcorr").checked;
});

// ----------------------------------------------------------------- submit

function buildLevelRequest() {
  const method = el("method").value === "__custom__" ? el("method-custom").value.trim() : el("method").value;
  const basisSel = el("basis").value;

  if (basisSel === "__genecp__") {
    const ecp_assignments = {};
    document.querySelectorAll(".ecp-check").forEach((cb) => {
      if (cb.checked) {
        const symbol = cb.dataset.el;
        const nameInput = document.querySelector(`.ecp-name[data-el="${symbol}"]`);
        ecp_assignments[symbol] = (nameInput.value || "LanL2DZ").trim();
      }
    });
    return {
      method,
      basis: "",
      genecp: { ecp_assignments, light_basis: el("genecp-light-basis").value.trim() },
    };
  }

  const basis = basisSel === "__custom__" ? el("basis-custom").value.trim() : basisSel;
  return { method, basis };
}

function showError(message) {
  el("form-error").textContent = message;
}

function selectedEnergyUnits() {
  return Array.from(document.querySelectorAll('input[name="energy-unit"]:checked')).map((cb) => cb.value);
}

el("job-form").addEventListener("submit", async (evt) => {
  evt.preventDefault();
  showError("");

  const type = studyType();
  if (type === "mechanism" || type === "single") {
    if (!uploads.reactant) {
      showError(type === "mechanism" ? "Upload a reactant file first." : "Upload a structure file first.");
      return;
    }
  }
  if (type === "mechanism" && !uploads.product) {
    showError("Upload a product file first.");
    return;
  }
  if (type === "mechanism" && selectedEnergyUnits().length === 0) {
    showError("Pick at least one energy unit.");
    return;
  }
  if (type === "ts_search") {
    const hasGuess = !!uploads.ts_guess;
    const hasPair = !!uploads.reactant && !!uploads.product;
    if (!hasGuess && !hasPair) {
      showError("Provide a TS guess, or both a reactant and a product.");
      return;
    }
  }

  const req = {
    study_type: type,
    job_name: el("job-name").value.trim() || "job",
    reactant_token: uploads.reactant ? uploads.reactant.token : null,
    product_token: (type === "mechanism" || type === "ts_search") && uploads.product ? uploads.product.token : null,
    ts_guess_token: uploads.ts_guess ? uploads.ts_guess.token : null,
    reactant_id: el("reactant-id").value.trim() || null,
    product_id: el("product-id").value.trim() || null,
    nprocs: parseInt(el("nprocs").value, 10) || 2,
    mem_gb: parseInt(el("mem-gb").value, 10) || 2,
    max_repair_attempts: parseInt(el("max-repair-attempts").value, 10) || 4,
    level: buildLevelRequest(),
    run_irc: type === "mechanism" ? el("run-irc").checked : false,
    irc_points: parseInt(el("irc-points").value, 10) || 25,
    energy_units: type === "mechanism" ? selectedEnergyUnits() : ["kcal/mol"],
    run_ts_distortion: type === "mechanism" ? el("run-ts-distortion").checked : false,
    distortion_factor: parseFloat(el("distortion-factor").value) || 1.0,
    run_irc_endpoint_reopt: type === "mechanism" ? el("run-irc-endpoint-reopt").checked : false,
    recover_missing_endpoint: type === "mechanism" ? el("recover-missing-endpoint").checked : false,
    skip_pm6_preopt: el("skip-pm6-preopt").checked,
    ts_recover_endpoints: type === "ts_search" ? el("ts-recover-endpoints").checked : false,
    ts_use_calcall: type === "ts_search" ? el("ts-calcall-fallback").checked : false,
    export_xyz: el("export-xyz").checked,
    export_cdxml: el("export-cdxml").checked,
    compute_gcorr: type !== "ts_search" ? el("compute-gcorr").checked : false,
    gcorr_temperature: parseFloat(el("gcorr-temperature").value) || 298.15,
    gcorr_temperature_unit: el("gcorr-temperature-unit").value,
    executor: pbsEnabled ? "pbs" : "local",
    pbs_script_template: pbsEnabled ? el("pbs-script-textarea").value : null,
  };

  el("submit-btn").disabled = true;
  try {
    const res = await fetch("/api/jobs", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(req),
    });
    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      throw new Error(body.detail || `HTTP ${res.status}`);
    }
    const { job_id } = await res.json();
    addStudyCard(job_id, req.job_name);
    el("job-form").classList.add("hidden");
  } catch (e) {
    showError(`Couldn't start the job: ${e.message}`);
  } finally {
    el("submit-btn").disabled = false;
  }
});

el("add-study-btn").addEventListener("click", () => {
  showError("");
  el("job-form").classList.remove("hidden");
  el("job-form").scrollIntoView({ behavior: "smooth", block: "start" });
});

// ---------------------------------------------------------------- studies
//
// Every submitted job gets its own card (newest first) with independent
// polling, so several studies can run side by side -- the form itself
// only ever starts one job at a time, but nothing stops the user from
// reopening it (via "+ Start another study") and submitting another
// while earlier ones are still going.

const TRASH_ICON = `<svg viewBox="0 0 16 16" width="14" height="14" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M2 4h12M5.5 4V2.5A1 1 0 0 1 6.5 1.5h3A1 1 0 0 1 10.5 2.5V4M6.5 7.5v4.5M9.5 7.5v4.5M3.5 4l.6 8.4A1 1 0 0 0 5.1 13.4h5.8a1 1 0 0 0 1-1.1L13 4"/></svg>`;

function addStudyCard(jobId, jobName) {
  const list = el("studies-list");
  const card = document.createElement("div");
  card.className = "study-card";
  card.dataset.jobId = jobId;
  card.innerHTML = `
    <div class="study-card-header">
      <span class="study-name">${jobName}</span>
      <div class="study-card-actions">
        <button type="button" class="stop-btn small-btn">Stop</button>
        <span class="badge running">Running</span>
        <button type="button" class="delete-btn" title="Remove this study entry" disabled>${TRASH_ICON}</button>
      </div>
    </div>
    <p class="stage-text"></p>
    <details class="study-log-details">
      <summary>Log</summary>
      <pre class="log-panel"></pre>
    </details>
    <div class="study-results"></div>
  `;
  list.prepend(card);
  el("studies-panel").classList.remove("hidden");

  const deleteBtn = card.querySelector(".delete-btn");
  deleteBtn.addEventListener("click", async () => {
    deleteBtn.disabled = true;
    try {
      const res = await fetch(`/api/jobs/${jobId}`, { method: "DELETE" });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.detail || `HTTP ${res.status}`);
      }
      card.remove();
      if (!list.children.length) {
        // Nothing left in the Studies list -- if the form is also
        // hidden (the normal state right after submitting a study),
        // there'd be no visible way back to it, since "+ Start
        // another study" lives inside this panel. Show the form
        // instead of just hiding an empty panel.
        el("studies-panel").classList.add("hidden");
        el("job-form").classList.remove("hidden");
      }
    } catch (e) {
      deleteBtn.disabled = false;
      deleteBtn.title = `Couldn't remove: ${e.message}`;
    }
  });

  const stopBtn = card.querySelector(".stop-btn");
  stopBtn.addEventListener("click", async () => {
    stopBtn.disabled = true;
    stopBtn.textContent = "Stopping...";
    try {
      await fetch(`/api/jobs/${jobId}/cancel`, { method: "POST" });
    } catch (e) {
      stopBtn.disabled = false;
      stopBtn.textContent = "Stop";
    }
  });

  pollStudy(jobId, jobName, card);
}

function pollStudy(jobId, jobName, card) {
  const badge = card.querySelector(".badge");
  const stopBtn = card.querySelector(".stop-btn");
  const deleteBtn = card.querySelector(".delete-btn");
  const stageText = card.querySelector(".stage-text");
  const logPanel = card.querySelector(".log-panel");
  const resultsDiv = card.querySelector(".study-results");

  const poll = async () => {
    let data;
    try {
      const res = await fetch(`/api/jobs/${jobId}`);
      data = await res.json();
    } catch (e) {
      stageText.textContent = "Lost contact with the server -- is it still running?";
      setTimeout(poll, 3000);
      return;
    }

    stageText.textContent = data.stage || "";
    logPanel.textContent = (data.log || []).join("\n");

    if (data.status === "running") {
      setTimeout(poll, 1500);
    } else if (data.status === "done") {
      stopBtn.remove();
      deleteBtn.disabled = false;
      badge.textContent = "Done";
      badge.className = "badge good";
      renderStudyResults(resultsDiv, data.result);
    } else if (data.status === "cancelled") {
      stopBtn.remove();
      deleteBtn.disabled = false;
      badge.textContent = "Cancelled";
      badge.className = "badge cancelled";
      const restartBtn = document.createElement("button");
      restartBtn.type = "button";
      restartBtn.className = "small-btn";
      restartBtn.textContent = "Restart";
      restartBtn.addEventListener("click", async () => {
        restartBtn.disabled = true;
        restartBtn.textContent = "Restarting...";
        try {
          const res = await fetch(`/api/jobs/${jobId}/restart`, { method: "POST" });
          if (!res.ok) {
            const body = await res.json().catch(() => ({}));
            throw new Error(body.detail || `HTTP ${res.status}`);
          }
          const { job_id } = await res.json();
          addStudyCard(job_id, jobName);
        } catch (e) {
          restartBtn.disabled = false;
          restartBtn.textContent = "Restart";
          resultsDiv.innerHTML = `<p class="error">Couldn't restart: ${e.message}</p>`;
        }
      });
      resultsDiv.innerHTML = "";
      resultsDiv.appendChild(restartBtn);
    } else {
      stopBtn.remove();
      deleteBtn.disabled = false;
      badge.textContent = "Failed";
      badge.className = "badge bad";
      resultsDiv.innerHTML = `<p class="error">${data.error || "The job failed."}</p>`;
    }
  };
  poll();
}

function row(label, value) {
  return `<div class="result-row"><span class="label">${label}</span><span class="value">${value}</span></div>`;
}


function renderReactionCoordinatePlot(result) {
  const units = result.energy_units || [];
  const unit = units.includes("kcal/mol") ? "kcal/mol" : units[0];
  if (!unit || !result.energies || !result.energies[unit]) return "";
  const e = result.energies[unit];
  const points = [
    { label: "Reactant", x: 0, y: 0 },
    { label: "TS", x: 0.5, y: e.ts },
    { label: "Product", x: 1, y: e.product },
  ];

  const width = 360, height = 190, padTop = 50, padBottom = 34, padX = 44;
  const plotW = width - 2 * padX, plotH = height - padTop - padBottom;
  const yMin = Math.min(0, ...points.map((p) => p.y));
  const yMax = Math.max(0, ...points.map((p) => p.y));
  const yRange = yMax - yMin || 1;

  const toXY = (p) => [padX + p.x * plotW, padTop + ((yMax - p.y) / yRange) * plotH];
  const [x0, y0] = toXY(points[0]);
  const [x1, y1] = toXY(points[1]);
  const [x2, y2] = toXY(points[2]);
  const mid1x = (x0 + x1) / 2, mid2x = (x1 + x2) / 2;
  const path = `M ${x0} ${y0} C ${mid1x} ${y0}, ${mid1x} ${y1}, ${x1} ${y1} C ${mid2x} ${y1}, ${mid2x} ${y2}, ${x2} ${y2}`;
  const digits = unit === "Hartree" ? 5 : 2;

  const markers = points
    .map((p) => {
      const [px, py] = toXY(p);
      return `<circle cx="${px}" cy="${py}" r="4" class="plot-point"></circle>
        <text x="${px}" y="${py - 10}" class="plot-value" text-anchor="middle">${p.y.toFixed(digits)}</text>
        <text x="${px}" y="${padTop + plotH + 18}" class="plot-label" text-anchor="middle">${p.label}</text>`;
    })
    .join("");

  return `
    <div class="reaction-plot">
      <button type="button" class="print-plot-btn" title="Print this plot">${PRINT_ICON}</button>
      <svg viewBox="0 0 ${width} ${height}" class="reaction-plot-svg">
        <text x="${padX}" y="14" class="plot-title">Reaction coordinate (${unit})</text>
        <line x1="${padX}" y1="${padTop + plotH}" x2="${width - padX}" y2="${padTop + plotH}" class="plot-axis"></line>
        <path d="${path}" class="plot-curve" fill="none"></path>
        ${markers}
      </svg>
    </div>
  `;
}

const PRINT_ICON = `<svg viewBox="0 0 16 16" width="14" height="14" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M4 5.5V1.5h8v4M4 11.5h-2a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-2M4 9h8v5.5H4z"/></svg>`;

function wirePrintButtons(container) {
  container.querySelectorAll(".print-plot-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      const svg = btn.closest(".reaction-plot").querySelector(".reaction-plot-svg");
      if (!svg) return;
      const win = window.open("", "_blank", "width=500,height=420");
      if (!win) return;
      win.document.write(`
        <!doctype html>
        <html><head><title>Reaction coordinate</title>
        <style>
          body { margin: 0; padding: 24px; background: #fff; color: #000; font-family: sans-serif; }
          svg { width: 100%; height: auto; }
          svg text { fill: #000; }
          svg .plot-curve { stroke: #000; }
          svg .plot-axis { stroke: #666; }
          svg .plot-point { fill: #000; }
        </style>
        </head><body>${svg.outerHTML}</body></html>
      `);
      win.document.close();
      win.onload = () => win.print();
    });
  });
}

function digitsFor(unit) {
  return unit === "Hartree" ? 5 : 2;
}

function renderResultsTables(compounds, units, result) {
  const hasGcorr = result.g_corr && Object.keys(result.g_corr).length > 0;
  const hasXyz = result.xyz_files && Object.keys(result.xyz_files).length > 0;
  const hasCdxml = result.cdxml_files && Object.keys(result.cdxml_files).length > 0;

  let energyHead = "<th>Sr No</th><th>Compound</th>";
  units.forEach((u) => (energyHead += `<th>Energy (${u})</th>`));
  if (hasGcorr) units.forEach((u) => (energyHead += `<th>G-corr (${u})</th>`));

  let energyBody = "";
  compounds.forEach((c) => {
    energyBody += `<tr><td>${c.no}</td><td>${c.label}</td>`;
    units.forEach((u) => {
      const v = c.energy(u);
      energyBody += `<td>${v == null ? "n/a" : v.toFixed(digitsFor(u))}</td>`;
    });
    if (hasGcorr) {
      units.forEach((u) => {
        const gc = result.g_corr[c.key];
        energyBody += `<td>${gc && gc[u] != null ? gc[u].toFixed(digitsFor(u)) : "n/a"}</td>`;
      });
    }
    energyBody += "</tr>";
  });

  let filesHead = "<th>Sr No</th><th>Compound</th><th>Logs</th>";
  if (hasXyz) filesHead += "<th>XYZ</th>";
  if (hasCdxml) filesHead += "<th>CDXML</th>";

  let filesBody = "";
  compounds.forEach((c) => {
    const logPath = (result.log_files || {})[c.key];
    filesBody += `<tr><td>${c.no}</td><td>${c.label}</td><td>${logPath || "n/a"}</td>`;
    if (hasXyz) {
      const xyzPath = (result.xyz_files || {})[c.key];
      filesBody += `<td>${xyzPath || "n/a"}</td>`;
    }
    if (hasCdxml) {
      const cdxmlPath = (result.cdxml_files || {})[c.key];
      filesBody += `<td>${cdxmlPath || "n/a"}</td>`;
    }
    filesBody += "</tr>";
  });

  return `
    <div class="results-tables">
      <div class="results-table-wrap"><table class="results-table"><thead><tr>${energyHead}</tr></thead><tbody>${energyBody}</tbody></table></div>
      <div class="results-table-wrap"><table class="results-table"><thead><tr>${filesHead}</tr></thead><tbody>${filesBody}</tbody></table></div>
    </div>
  `;
}

function renderStudyResults(content, result) {
  if (!result) {
    content.innerHTML = "<p>No result data.</p>";
    return;
  }

  if (result.type === "single") {
    const compounds = [{ no: 1, label: "Structure", key: "final", energy: () => result.zpe_energy ?? result.scf_energy }];
    content.innerHTML =
      row("Job", result.job_name) +
      `<div class="results-layout">` +
      renderResultsTables(compounds, ["Hartree"], result) +
      `</div>` +
      row("Files", result.out_dir);
    return;
  }

  if (result.type === "ts_search") {
    const overlapRow = result.match_overlap != null
      ? row("TS/reaction overlap", result.match_overlap.toFixed(2))
      : row("TS/reaction overlap", "n/a (no reactant/product given to check against)");

    let recoveryRows = "";
    const rec = result.recovery;
    if (rec) {
      if (rec.classified) {
        recoveryRows += row("Recovered reactant", rec.reactant_log || "not recovered");
        recoveryRows += row("Recovered product", rec.product_log || "not recovered");
      } else {
        recoveryRows += row("Recovered side A", `${rec.side_a_log || "not recovered"} (reactant or product -- not determined which)`);
        recoveryRows += row("Recovered side B", `${rec.side_b_log || "not recovered"} (reactant or product -- not determined which)`);
      }
    }

    const hasXyz = result.xyz_files && Object.keys(result.xyz_files).length > 0;
    const hasCdxml = result.cdxml_files && Object.keys(result.cdxml_files).length > 0;
    // Only present once there's a usable reactant AND product -- either
    // given directly to the TS search and independently optimized, or
    // recovered from the TS -- letting this section show the same
    // reaction-coordinate report the mechanism study does, per your
    // request to be able to extract that data here too.
    const hasReactionCoordinate = result.energies && Object.keys(result.energies).length > 0;

    const sourceLabel = { ts_distortion: "recovered from the TS (distortion + reopt)" };
    let sourceRows = "";
    if (hasReactionCoordinate) {
      if (result.reactant_source && result.reactant_source !== "guess") {
        sourceRows += row("Reactant source", sourceLabel[result.reactant_source] || result.reactant_source);
      }
      if (result.product_source && result.product_source !== "guess") {
        sourceRows += row("Product source", sourceLabel[result.product_source] || result.product_source);
      }
    }

    content.innerHTML =
      row("Job", result.job_name) +
      row("TS found", '<span class="badge good">yes</span>') +
      row("Imaginary freq", `${result.imaginary_freq.toFixed(1)} cm⁻¹`) +
      overlapRow +
      row("TS log", (result.log_files || {}).ts || "n/a") +
      (hasXyz && !hasReactionCoordinate ? row("TS XYZ", (result.xyz_files || {}).ts || "n/a") : "") +
      (hasCdxml && !hasReactionCoordinate ? row("TS CDXML", (result.cdxml_files || {}).ts || "n/a") : "") +
      recoveryRows +
      sourceRows +
      (hasReactionCoordinate
        ? `<div class="results-layout">${renderResultsTables(
            [
              { no: 1, label: "Reactant", key: "reactant", energy: () => 0 },
              { no: 2, label: "TS", key: "ts", energy: (u) => result.energies[u].ts },
              { no: 3, label: "Product", key: "product", energy: (u) => result.energies[u].product },
            ],
            result.energy_units || [],
            result
          )}${renderReactionCoordinatePlot(result)}</div>`
        : "") +
      row("Files", result.out_dir);
    if (hasReactionCoordinate) wirePrintButtons(content);
    return;
  }

  const ircBadge =
    result.irc_ran === false
      ? '<span class="badge">skipped</span>'
      : result.irc_connected
      ? '<span class="badge good">connected</span>'
      : '<span class="badge bad">needs review</span>';

  const sourceLabel = { guess: "original optimization", ts_distortion: "TS-mode distortion", irc_reopt: "IRC endpoint reopt" };
  let sourceRows = "";
  if (result.reactant_source && result.reactant_source !== "guess") {
    const why = result.reactant_recovered ? "recovered -- original optimization failed" : "more stable than the original optimization";
    sourceRows += row("Reactant source", `${sourceLabel[result.reactant_source] || result.reactant_source} (${why})`);
  }
  if (result.product_source && result.product_source !== "guess") {
    const why = result.product_recovered ? "recovered -- original optimization failed" : "more stable than the original optimization";
    sourceRows += row("Product source", `${sourceLabel[result.product_source] || result.product_source} (${why})`);
  }

  const units = result.energy_units || [];
  const compounds = [
    { no: 1, label: "Reactant", key: "reactant", energy: () => 0 },
    { no: 2, label: "TS", key: "ts", energy: (u) => result.energies[u].ts },
    { no: 3, label: "Product", key: "product", energy: (u) => result.energies[u].product },
  ];

  content.innerHTML =
    row("Job", result.job_name) +
    sourceRows +
    row("TS imaginary freq", `${result.ts_imaginary_freq.toFixed(1)} cm⁻¹`) +
    row("TS/reaction overlap", result.ts_match_overlap.toFixed(2)) +
    row("IRC", ircBadge) +
    `<div class="results-layout">` +
    renderResultsTables(compounds, units, result) +
    renderReactionCoordinatePlot(result) +
    `</div>` +
    row("Files", result.out_dir);
  wirePrintButtons(content);
}
