"""
llm_assist.py

Optional LLM-assisted structure refinement: given a free-text
description (a reaction, a compound's common/IUPAC name, or just
informal notes) alongside a SMILES/file-derived structure, asks Claude
to read the description and suggest how to get the best starting
geometry -- a cleaned-up PubChem search query, a corrected SMILES if
the one given looks inconsistent with the description, and
charge/multiplicity if the description implies something non-default
(a radical, an ion, a triplet).

Geometry itself is still only ever generated by the existing
deterministic tools (RDKit, PubChem) -- LLMs aren't reliable at
producing precise 3D coordinates directly, so this is scoped to what
they're actually good at: reading text and picking a good lookup key.
The suggestion is advisory; nothing here silently overwrites a
structure -- callers (webapp.py) show it to the user to accept or
ignore, and re-verify any suggested alternate structure's formula
against the original before offering it.

Needs an Anthropic credential (ANTHROPIC_API_KEY, or another source
the SDK resolves automatically). This is the one piece of gaussbot
that isn't fully local/deterministic -- if no credential is
available, is_available() returns False and callers should skip this
step entirely rather than block on it.
"""

from __future__ import annotations

import os
from typing import Optional

from pydantic import BaseModel

MODEL = "claude-opus-5"


class LLMUnavailableError(RuntimeError):
    """Raised when there's no Anthropic credential available, or the API
    call itself fails -- callers should catch this and skip the LLM
    step rather than treat it as a hard pipeline failure."""


class StructureHint(BaseModel):
    matches_description: bool
    notes: str
    suggested_pubchem_query: Optional[str] = None
    suggested_smiles: Optional[str] = None
    suggested_charge: Optional[int] = None
    suggested_multiplicity: Optional[int] = None


_SYSTEM_PROMPT = """\
You help set up a starting geometry for a Gaussian quantum chemistry \
calculation. You're given a free-text description the user wrote (a \
reaction, a compound's common or IUPAC name, or informal notes) \
alongside the SMILES string and molecular formula the pipeline is \
about to use as the starting structure.

Actual 3D geometry generation is handled by deterministic tools \
(RDKit embedding, PubChem lookup) -- you never invent coordinates. \
Your job is narrower: read the description and suggest how to get a \
better starting point for those tools, or flag a real mismatch.

- If the description names a specific compound, suggest a clean \
PubChem search query (a name or synonym PubChem is likely to \
recognize) so the pipeline can fetch a database-verified 3D structure \
instead of a generic embedding. Leave this null if the description \
doesn't identify a specific compound.
- Only suggest a corrected SMILES if the given one looks genuinely \
inconsistent with the description (wrong connectivity, wrong atom, \
clearly the wrong molecule) -- not for stylistic differences. Leave \
it null when the given SMILES already looks right.
- Only suggest charge/multiplicity if the description implies \
something other than a neutral closed-shell singlet -- e.g. it says \
"radical", "anion", "cation", "triplet", "diradical". Leave both null \
otherwise.
- Set matches_description to false only if you think the given SMILES \
and the description describe different molecules, not for minor \
ambiguity.
- Be conservative. If you're not confident, say so in notes and leave \
the suggestion fields null rather than guessing.
"""


def is_available() -> bool:
    """Best-effort, no-network-call check for whether an Anthropic
    credential is likely configured. A profile from `ant auth login`
    also works but can't be checked this cheaply -- refine_structure()
    itself is the definitive answer either way."""
    if os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_AUTH_TOKEN"):
        try:
            import anthropic  # noqa: F401
        except ImportError:
            return False
        return True
    return False


def refine_structure(
    description: str,
    smiles: Optional[str],
    formula: str,
    label: str = "structure",
) -> StructureHint:
    """
    Ask Claude to read `description` and suggest a better starting
    point for `smiles`/`formula` -- a PubChem query, a corrected
    SMILES, or charge/multiplicity -- or flag a mismatch. Raises
    LLMUnavailableError if no Anthropic credential is available, or the
    call itself fails; callers should catch that and skip this step.
    """
    try:
        import anthropic
    except ImportError as e:
        raise LLMUnavailableError("the 'anthropic' package isn't installed") from e

    try:
        client = anthropic.Anthropic()
    except Exception as e:
        raise LLMUnavailableError(f"couldn't set up an Anthropic client: {e}") from e

    user_content = (
        f"Description: {description}\n"
        f"Label: {label}\n"
        f"Given SMILES: {smiles or '(none -- loaded from a file, not SMILES)'}\n"
        f"Molecular formula: {formula}\n"
    )

    try:
        response = client.messages.parse(
            model=MODEL,
            max_tokens=4096,
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_content}],
            output_format=StructureHint,
        )
    except Exception as e:
        raise LLMUnavailableError(f"Anthropic request failed: {e}") from e

    if response.stop_reason == "refusal":
        raise LLMUnavailableError("Claude declined this request")

    return response.parsed_output
